# Site settings
title: Geostatistics
email: bryanlzhou@gmail.com
description:
baseurl:  # the subpath of your site, e.g. /blog
url: https://bryanlizhou.github.io # the base hostname & protocol for your site
author: Bryan Zhou
street_address:
city:
state:
zip_code:
country:
phone:

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/?lang=en

# Build settings
markdown: kramdown

sass:
style: compressed
